- name: copy kube-proxy ssl 
  copy:
    src: "files/ssl/{{ item }}"
    dest: "{{ ca_dir }}/{{ item }}"
  with_items:
    - kube-proxy.pem
    - kube-proxy-key.pem
- name: create kube-proxy work directory 
  file:
    name: "{{ base_dir }}/kube-proxy/{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - logs 
    - conf

- name: copy kube-proxy binary file
  copy:
    src: bin/kubernetes/kube-proxy 
    dest: "{{ bin_dir }}/kube-proxy"
    mode: 0755 

- name: set-cluster kube-proxy 
  delegate_to: "{{ groups['kube-master'][0] }}"
  shell: "{{ bin_dir }}/kubectl config set-cluster kubernetes \
         --certificate-authority={{ ca_dir }}/ca.pem \
         --embed-certs=true \
         --server=https://127.0.0.1:8443 \
         --kubeconfig={{ base_dir }}/kube-proxy/conf/kube-proxy.kubeconfig"
  ignore_errors: true

- name: set-credentials kube-proxy
  delegate_to: "{{ groups['kube-master'][0] }}"
  shell: "{{ bin_dir }}/kubectl config set-credentials kube-proxy \
         --client-certificate={{ ca_dir }}/kube-proxy.pem \
         --client-key={{ ca_dir }}/kube-proxy-key.pem \
         --embed-certs=true \
         --kubeconfig={{ base_dir }}/kube-proxy/conf/kube-proxy.kubeconfig"
  ignore_errors: true

- name: set-context kube-proxy
  delegate_to: "{{ groups['kube-master'][0] }}"
  shell: "{{ bin_dir }}/kubectl config set-context default \
         --cluster=kubernetes \
         --user=kube-proxy \
         --kubeconfig={{ base_dir }}/kube-proxy/conf/kube-proxy.kubeconfig"
  ignore_errors: true

- name: use-context kube-proxy
  delegate_to: "{{ groups['kube-master'][0] }}"
  shell: "{{ bin_dir }}/kubectl config use-context default \
         --kubeconfig={{ base_dir }}/kube-proxy/conf/kube-proxy.kubeconfig"
  ignore_errors: true

- name: copy kube-proxy kubeconfig
  copy: 
    src: "{{ base_dir }}/kube-proxy/conf/kube-proxy.kubeconfig"
    dest: "{{ base_dir }}/kube-proxy/conf/kube-proxy.kubeconfig"

- name: copy kube-proxy config file 
  template:
    src: kube-proxy.yaml.j2
    dest: "{{ base_dir }}/kube-proxy/conf/kube-proxy.yaml"

- name: copy kube-proxy systemd file 
  template:
    src: kube-proxy.service.j2
    dest: /usr/lib/systemd/system/kube-proxy.service

- name: start kube-proxy
  systemd:
    name: kube-proxy
    state: restarted
    daemon_reload: yes
    enabled: yes
